import { NextRequest, NextResponse } from 'next/server';
import { getBanners, addBanner } from '@/lib/storage';
import { Banner } from '@/types/banner';

// Force dynamic rendering to prevent caching
export const dynamic = 'force-dynamic';
export const revalidate = 0;

export async function GET() {
  try {
    const banners = await getBanners();
    console.log('API GET /api/banners - Returning banners:', banners.map(b => ({ id: b.id, position: b.position })));
    return NextResponse.json(banners, {
      headers: {
        'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0',
      },
    });
  } catch (error) {
    console.error('Error fetching banners:', error);
    return NextResponse.json(
      { error: 'Failed to fetch banners' },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { imageUrl, link, title, expiresAt } = body;

    if (!imageUrl || !link) {
      return NextResponse.json(
        { error: 'Image URL and link are required' },
        { status: 400 }
      );
    }

    const bannerToAdd: Banner = {
      id: '', // Will be generated by Supabase
      imageUrl,
      link,
      title: title || '',
      createdAt: new Date().toISOString(),
      expiresAt: expiresAt || null,
    };

    const newBanner = await addBanner(bannerToAdd);

    return NextResponse.json(newBanner, { status: 201 });
  } catch (error) {
    console.error('Error adding banner:', error);
    return NextResponse.json(
      { error: 'Failed to add banner' },
      { status: 500 }
    );
  }
}
