import { NextRequest, NextResponse } from 'next/server';
import { getBanners, addBanner } from '@/lib/storage';
import { Banner } from '@/types/banner';

export async function GET() {
  try {
    const banners = await getBanners();
    return NextResponse.json(banners);
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to fetch banners' },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { imageUrl, link, title, position } = body;

    if (!imageUrl || !link) {
      return NextResponse.json(
        { error: 'Image URL and link are required' },
        { status: 400 }
      );
    }

    const bannerToAdd: Banner = {
      id: '', // Will be generated by Supabase
      imageUrl,
      link,
      title: title || '',
      createdAt: new Date().toISOString(),
      position: position ?? null,
    };

    const newBanner = await addBanner(bannerToAdd);

    return NextResponse.json(newBanner, { status: 201 });
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to add banner' },
      { status: 500 }
    );
  }
}
