import { NextRequest, NextResponse } from 'next/server';
import { getBanners, addBanner } from '@/lib/storage';
import { Banner } from '@/types/banner';

// Allow caching for better performance, revalidate every 60 seconds
export const revalidate = 60;

export async function GET() {
  try {
    const banners = await getBanners();
    return NextResponse.json(banners, {
      headers: {
        'Cache-Control': 'public, s-maxage=60, stale-while-revalidate=120',
      },
    });
  } catch (error) {
    console.error('Error fetching banners:', error);
    return NextResponse.json(
      { error: 'Failed to fetch banners' },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { imageUrl, link, title, expiresAt } = body;

    if (!imageUrl || !link) {
      return NextResponse.json(
        { error: 'Image URL and link are required' },
        { status: 400 }
      );
    }

    const bannerToAdd: Banner = {
      id: '', // Will be generated by Supabase
      imageUrl,
      link,
      title: title || '',
      createdAt: new Date().toISOString(),
      expiresAt: expiresAt || null,
    };

    const newBanner = await addBanner(bannerToAdd);

    return NextResponse.json(newBanner, { status: 201 });
  } catch (error) {
    console.error('Error adding banner:', error);
    return NextResponse.json(
      { error: 'Failed to add banner' },
      { status: 500 }
    );
  }
}
